---
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: single_quotes
Style/FormatStringToken:
  EnforcedStyle: 'template'
Style/SymbolArray:
  EnforcedStyle: brackets
Naming/AsciiIdentifiers:
  Enabled: false
AllCops:
  SuggestExtensions: false
